version: "3.8"

services:
  db:
    # Defines the 'db' service for MySQL database
    image: mysql:8.0 # Uses the MySQL 8.0 Docker image
    environment:
      # Sets environment variables for the database configuration
      - MYSQL_DATABASE=appdb # Specifies the name of the database
      - MYSQL_PASSWORD=pass123 # Sets the password for the MySQL user
      - MYSQL_ROOT_PASSWORD=pass123 # Sets the root password for MySQL
    networks:
      - sameNetworkAsMysql # Connects the service to the 'sameNetworkAsMysql' network
    ports:
      - 3307:3306 # Maps the container's port 3306 to the host's port 3307
    volumes:
      - db-data:/var/lib/mysql # Mounts the volume to persist MySQL data

  app:
    # Defines the 'app' service for the Next.js app
    build:
      # Builds the Next.js app using the provided Dockerfile
      context: .
      target: runner # Uses the runner stage from the multi-stage Dockerfile
    environment:
      NODE_ENV: production
      HOSTNAME: "0.0.0.0"
      PORT: 3000
    ports:
      - 3000:3000 # Maps the container's port 3000 to the host's port 3000
    networks:
      - sameNetworkAsMysql # Connects the service to the 'sameNetworkAsMysql' network
    depends_on:
      - db # Specifies that the 'app' service depends on the 'db' service

networks:
  sameNetworkAsMysql:
    # Defines the 'sameNetworkAsMysql' network
    driver: bridge # Specifies the network driver as 'bridge'

volumes:
  db-data: # Defines the volume for MySQL data
