-- AlterTable
ALTER TABLE `Team` MODIFY `home_ground` VARCHAR(191) NOT NULL DEFAULT '',
    MODIFY `owner` VARCHAR(191) NOT NULL DEFAULT '',
    MODIFY `coach` VARCHAR(191) NOT NULL DEFAULT '',
    MODIFY `captain` VARCHAR(191) NOT NULL DEFAULT '';
