import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Container, Theme, ThemePanel } from "@radix-ui/themes";
import "@radix-ui/themes/styles.css";
import "./theme-config.css";
import Navbar from "./Navbar";
import { Toaster } from "@/components/ui/toaster";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Team Builder",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Theme accentColor="indigo">
          <Navbar />
          <main className="p-5">
            <Container>{children}</Container>
          </main>
          <Toaster />
        </Theme>
      </body>
    </html>
  );
}
